package com.hermes.client.ui.theme

import androidx.compose.ui.graphics.Color

// Anthropic / Claude palette, ported from RikkaHub's "Claude" preset
// (ivory + terracotta). Warm neutral surfaces, clay-orange accent.

// Light
val LightPrimary = Color(0xFFC96442)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFF7E3D9)
val LightOnPrimaryContainer = Color(0xFF8A3E23)
val LightSecondary = Color(0xFF6F675C)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE9E6DC)
val LightOnSecondaryContainer = Color(0xFF3D3929)
val LightTertiary = Color(0xFF9A6C3E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFEBDBBC)
val LightOnTertiaryContainer = Color(0xFF5A4526)
val LightError = Color(0xFFB03D2E)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFF8E1DC)
val LightOnErrorContainer = Color(0xFF7E2418)
val LightBackground = Color(0xFFFAF9F5)
val LightOnBackground = Color(0xFF262624)
val LightSurface = Color(0xFFFAF9F5)
val LightOnSurface = Color(0xFF262624)
val LightSurfaceVariant = Color(0xFFEDEAE0)
val LightOnSurfaceVariant = Color(0xFF6F675C)
val LightOutline = Color(0xFFBDB7A9)
val LightOutlineVariant = Color(0xFFE5E1D6)
val LightInverseSurface = Color(0xFF33312C)
val LightInverseOnSurface = Color(0xFFF7F5EF)
val LightInversePrimary = Color(0xFFFFB59B)
val LightSurfaceDim = Color(0xFFE7E3D8)
val LightSurfaceBright = Color(0xFFFFFFFF)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF7F5EF)
val LightSurfaceContainer = Color(0xFFF2F0E8)
val LightSurfaceContainerHigh = Color(0xFFEDEAE0)
val LightSurfaceContainerHighest = Color(0xFFE7E3D8)

// Dark
val DarkPrimary = Color(0xFFE4906E)
val DarkOnPrimary = Color(0xFF4A1B0B)
val DarkPrimaryContainer = Color(0xFF7A3620)
val DarkOnPrimaryContainer = Color(0xFFFFDBCE)
val DarkSecondary = Color(0xFFD3CCBF)
val DarkOnSecondary = Color(0xFF383429)
val DarkSecondaryContainer = Color(0xFF4A453A)
val DarkOnSecondaryContainer = Color(0xFFEDE7DA)
val DarkTertiary = Color(0xFFE0BE8C)
val DarkOnTertiary = Color(0xFF422C0C)
val DarkTertiaryContainer = Color(0xFF5C4525)
val DarkOnTertiaryContainer = Color(0xFFFFDDB0)
val DarkError = Color(0xFFFFB4A6)
val DarkOnError = Color(0xFF5F1508)
val DarkErrorContainer = Color(0xFF82271A)
val DarkOnErrorContainer = Color(0xFFFFDAD3)
val DarkBackground = Color(0xFF1F1E1D)
val DarkOnBackground = Color(0xFFEDEAE3)
val DarkSurface = Color(0xFF1F1E1D)
val DarkOnSurface = Color(0xFFEDEAE3)
val DarkSurfaceVariant = Color(0xFF3A372F)
val DarkOnSurfaceVariant = Color(0xFFCBC5B8)
val DarkOutline = Color(0xFF5A564C)
val DarkOutlineVariant = Color(0xFF3A372F)
val DarkInverseSurface = Color(0xFFEDEAE3)
val DarkInverseOnSurface = Color(0xFF33312C)
val DarkInversePrimary = Color(0xFFC96442)
val DarkSurfaceDim = Color(0xFF1F1E1D)
val DarkSurfaceBright = Color(0xFF44423E)
val DarkSurfaceContainerLowest = Color(0xFF171614)
val DarkSurfaceContainerLow = Color(0xFF262624)
val DarkSurfaceContainer = Color(0xFF2B2A27)
val DarkSurfaceContainerHigh = Color(0xFF343230)
val DarkSurfaceContainerHighest = Color(0xFF3E3C37)

// Code block (kept dark-ish in both themes for contrast with syntax colors)
val CodeBackgroundLight = Color(0xFF2B2A27)
val CodeBackgroundDark = Color(0xFF171614)

// Syntax (warm-leaning accents that sit well on the Claude palette)
val SyntaxKeyword = Color(0xFFE4906E)
val SyntaxString = Color(0xFFA6C68A)
val SyntaxComment = Color(0xFF8A857A)
val SyntaxNumber = Color(0xFFE0BE8C)
val SyntaxFunction = Color(0xFF9BB8D3)
val SyntaxType = Color(0xFFE6C37A)
val SyntaxPlain = Color(0xFFEDEAE3)
