package com.hermes.client.ui.theme

import androidx.compose.ui.graphics.Color

// Light
val LightPrimary = Color(0xFF6750A4)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFEADDFF)
val LightOnPrimaryContainer = Color(0xFF21005D)
val LightSecondary = Color(0xFF625B71)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE8DEF8)
val LightOnSecondaryContainer = Color(0xFF1D192B)
val LightTertiary = Color(0xFF7D5260)
val LightTertiaryContainer = Color(0xFFFFD8E4)
val LightBackground = Color(0xFFFDF8FF)
val LightOnBackground = Color(0xFF1C1B1F)
val LightSurface = Color(0xFFFDF8FF)
val LightOnSurface = Color(0xFF1C1B1F)
val LightSurfaceVariant = Color(0xFFE7E0EC)
val LightOnSurfaceVariant = Color(0xFF49454F)
val LightOutline = Color(0xFF7A757F)
val LightOutlineVariant = Color(0xFFCAC4D0)
val LightSurfaceContainer = Color(0xFFF3EDF7)
val LightSurfaceContainerHigh = Color(0xFFECE6F0)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)

// Dark
val DarkPrimary = Color(0xFFD0BCFF)
val DarkOnPrimary = Color(0xFF381E72)
val DarkPrimaryContainer = Color(0xFF4F378B)
val DarkOnPrimaryContainer = Color(0xFFEADDFF)
val DarkSecondary = Color(0xFFCCC2DC)
val DarkOnSecondary = Color(0xFF332D41)
val DarkSecondaryContainer = Color(0xFF4A4458)
val DarkOnSecondaryContainer = Color(0xFFE8DEF8)
val DarkTertiary = Color(0xFFEFB8C8)
val DarkTertiaryContainer = Color(0xFF633B48)
val DarkBackground = Color(0xFF141218)
val DarkOnBackground = Color(0xFFE6E1E5)
val DarkSurface = Color(0xFF141218)
val DarkOnSurface = Color(0xFFE6E1E5)
val DarkSurfaceVariant = Color(0xFF49454F)
val DarkOnSurfaceVariant = Color(0xFFCAC4D0)
val DarkOutline = Color(0xFF938F99)
val DarkOutlineVariant = Color(0xFF49454F)
val DarkSurfaceContainer = Color(0xFF211F26)
val DarkSurfaceContainerHigh = Color(0xFF2B2930)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)

// Code block (kept dark-ish in both themes for contrast with syntax colors)
val CodeBackgroundLight = Color(0xFF1E1E2E)
val CodeBackgroundDark = Color(0xFF11111B)

// Syntax
val SyntaxKeyword = Color(0xFFCBA6F7)
val SyntaxString = Color(0xFFA6E3A1)
val SyntaxComment = Color(0xFF6C7086)
val SyntaxNumber = Color(0xFFFAB387)
val SyntaxFunction = Color(0xFF89B4FA)
val SyntaxType = Color(0xFFF9E2AF)
val SyntaxPlain = Color(0xFFCDD6F4)
